### PR TITLE
Fix OSX project reload

### PR DESCRIPTION
**Pull request by blunt1337**

### CODE REVIEW

**Comment by ghost** [comment]
Hello, thanks for the pr, I have a question

``` go
    err = proc.Release()
    if err != nil {
        return nil // to prevent throw an error if the proc is not yet started correctly (= previous build error)
}
```

so  `.Release()` check doesn't works on OSX?

**Comment by blunt1337** [comment]
You're right, the following code is better:

``` go
err = proc.Release()
if err != nil {
    return nil // to prevent throw an error if the proc is not yet started correctly (= previous build error)
}
if proc.Pid <= 0 {
    return nil
}
```

**Comment by blunt1337** [comment]
Also, the fsnotify dispatch 3 events (CHMOD + WRITE + CHMOD) for 1 file modification, so it recompile 3 times. If you have an idea how to fix this, i can test it out.

**Comment by blunt1337** [comment]
The best solution that i found was to ignore the event with:

``` go
if event.Op & fsnotify.Chmod == fsnotify.Chmod {
    continue
}
```

**Comment by kataras** [comment]
make a second pull request with both of these changes, you made a good start, keep going!

**Comment by ghost** [comment]
make a second pull request with both of these changes, you made a good start, keep going!

> Don't forget to star this project if you liked it:)

**Comment by blunt1337** [comment]
Thanks, i'm still new in Go. I just started sunday that i already have PHP errors with missing ";"

**Comment by kataras** [comment]
ahah yes I understand you, I was Java, C# and Nodejs developer for a decade, you will learn fast, don't worry about it

**Pull request merged**
